/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.EF;

import java.util.ArrayList;
import model.accountsTableModel;

/**
 *
 * @author Scarleth
 */
public class FrmBG extends javax.swing.JFrame {

    /**
     * Creates new form FrmBG
     */
    public FrmBG() {
        initComponents();
    }
    
    
    //DATASET
    public void setData(ArrayList<accountsTableModel> activos,ArrayList<accountsTableModel> pasivos,ArrayList<accountsTableModel> capital,String Empresa, String Periodo, String Balance,String TotAct,String TotPas,String TotCap){
        String[][] tbActivos = new String[activos.size()][2];
        String[][] tbPasivos = new String[pasivos.size()][2];
        String[][] tbCapital = new String[capital.size()][2];
        
        for(int i=0; i < activos.size(); i++){
            tbActivos[i][0] = activos.get(i).getCuenta();
            tbActivos[i][1] = activos.get(i).getMonto();
        }
        
        for(int j=0; j < pasivos.size(); j++){
            tbPasivos[j][0] = pasivos.get(j).getCuenta();
            tbPasivos[j][1] = pasivos.get(j).getMonto();
        }
        
        for(int k=0; k< capital.size(); k++){
            tbCapital[k][0] = capital.get(k).getCuenta();
            tbCapital[k][1] = capital.get(k).getMonto();
        }
        
        TblActivos.setModel(new javax.swing.table.DefaultTableModel(
            tbActivos,
            new String [] {
                "ACTIVOS", "MONTO"
            }
        ));
        
        TblPasivos.setModel(new javax.swing.table.DefaultTableModel(
            tbPasivos,
            new String [] {
                "PASIVOS", "MONTO"
            }
        ));
        
        TblCapital.setModel(new javax.swing.table.DefaultTableModel(
            tbCapital,
            new String [] {
                "CAPITAL", "MONTO"
            }
        ));
        
        BG.setText(Empresa);
        lblPeriodo.setText(Periodo);
        lblBalance.setText(Balance);
        lblTotActivos.setText(TotAct);
        lblTotPasivos.setText(TotPas);
        lblTotCapital.setText(TotCap);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblActivos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblTotActivos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblPasivos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblTotPasivos = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblCapital = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblTotCapital = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BALANCE GENERAL");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));

        TblActivos.setBackground(new java.awt.Color(255, 255, 255));
        TblActivos.setForeground(new java.awt.Color(0, 0, 0));
        TblActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ACTIVOS", "MONTO"
            }
        ));
        TblActivos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(TblActivos);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TOTAL DE ACTIVOS:");

        lblTotActivos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotActivos.setForeground(new java.awt.Color(0, 0, 0));
        lblTotActivos.setText("00000");

        TblPasivos.setBackground(new java.awt.Color(255, 255, 255));
        TblPasivos.setForeground(new java.awt.Color(0, 0, 0));
        TblPasivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PASIVOS", "MONTO"
            }
        ));
        TblPasivos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(TblPasivos);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TOTAL DE PASIVOS:");

        lblTotPasivos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotPasivos.setForeground(new java.awt.Color(0, 0, 0));
        lblTotPasivos.setText("00000");

        BG.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BG.setForeground(new java.awt.Color(0, 0, 0));
        BG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BG.setText("BALANCE GENERAL");

        lblEmpresa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("BALANCE GENERAL");

        lblPeriodo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        lblPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeriodo.setText("00/00/00");

        TblCapital.setBackground(new java.awt.Color(255, 255, 255));
        TblCapital.setForeground(new java.awt.Color(0, 0, 0));
        TblCapital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CAPITAL", "MONTO"
            }
        ));
        TblCapital.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setViewportView(TblCapital);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TOTAL DE CAPITAL:");

        lblTotCapital.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotCapital.setForeground(new java.awt.Color(0, 0, 0));
        lblTotCapital.setText("00000");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ACTIVOS  = PASIVOS + CAPITAL ");

        lblBalance.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBalance.setForeground(new java.awt.Color(0, 0, 0));
        lblBalance.setText("0000 = 0000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(lblPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(148, 148, 148)
                        .addComponent(lblTotCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(63, 63, 63)
                        .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(145, 145, 145)
                                    .addComponent(lblTotPasivos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(108, 108, 108))))
                .addGap(411, 411, 411))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotActivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblTotPasivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotCapital)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBalance))
                .addGap(103, 103, 103))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTable TblActivos;
    private javax.swing.JTable TblCapital;
    private javax.swing.JTable TblPasivos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblTotActivos;
    private javax.swing.JLabel lblTotCapital;
    private javax.swing.JLabel lblTotPasivos;
    // End of variables declaration//GEN-END:variables
}
