/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.EF;

import java.util.ArrayList;
import model.accountsTableModel;

/**
 *
 * @author Scarleth
 */
public class FrmER extends javax.swing.JFrame {

    /**
     * Creates new form FrmER
     */
    public FrmER() {
        initComponents();
    }

    //DATASET
    public void setData(ArrayList<accountsTableModel> ingresos, ArrayList<accountsTableModel> costos,
            ArrayList<accountsTableModel> gastos, ArrayList<accountsTableModel> desdev, ArrayList<accountsTableModel> IngGasNoOpe, String Empresa, String Periodo, float totingresos, float totcostos, float totgastos, float utilidadB, float utilidadOP,
            float utilidadantimp, float impuestos, float utilidadneta, float utilidadretenida, String dividendos) {

        if (ingresos.size() > 0) {
            String[][] tbIngresos = new String[ingresos.size()][2];
            for (int i = 0; i < ingresos.size(); i++) {
                tbIngresos[i][0] = ingresos.get(i).getCuenta();
                tbIngresos[i][1] = ingresos.get(i).getMonto();
            }

            TblIngresos.setModel(new javax.swing.table.DefaultTableModel(
                    tbIngresos,
                    new String[]{
                        "INGRESOS", "MONTO C$"
                    }
            ));
        }
        if (costos.size() > 0) {
            String[][] tbCostos = new String[costos.size()][2];
        
            for (int j = 0; j < costos.size(); j++) {
                tbCostos[j][0] = costos.get(j).getCuenta();
                tbCostos[j][1] = costos.get(j).getMonto();
            }
            TblCostos.setModel(new javax.swing.table.DefaultTableModel(
                    tbCostos,
                    new String[]{
                        "COSTOS ", "MONTO C$"
                    }
            ));

        }
        if (gastos.size() > 0) {
            String[][] tbGastos = new String[gastos.size()][2];
        
            for (int k = 0; k < gastos.size(); k++) {
                tbGastos[k][0] = gastos.get(k).getCuenta();
                tbGastos[k][1] = gastos.get(k).getMonto();
            }
            TblGastos.setModel(new javax.swing.table.DefaultTableModel(
                    tbGastos,
                    new String[]{
                        "GASTOS", "MONTO C$"
                    }
            ));

        }
        if (desdev.size() > 0) {
            String[][] tbDesdev = new String[desdev.size()][2];
        
            for (int l = 0; l < desdev.size(); l++) {
                tbDesdev[l][0] = desdev.get(l).getCuenta();
                tbDesdev[l][1] = desdev.get(l).getMonto();
            }
            TblDesDev.setModel(new javax.swing.table.DefaultTableModel(
                    tbDesdev,
                    new String[]{
                        "(-) Descuentos y devoluciones", "MONTO C$"
                    }
            ));

        }
        if (IngGasNoOpe.size() > 0) {
            String[][] tbIngGasNoOpe = new String[IngGasNoOpe.size()][2];
            
            for (int m = 0; m < IngGasNoOpe.size(); m++) {
                tbIngGasNoOpe[m][0] = IngGasNoOpe.get(m).getCuenta();
                tbIngGasNoOpe[m][1] = IngGasNoOpe.get(m).getMonto();
            }

            TblIngGasNoOpe.setModel(new javax.swing.table.DefaultTableModel(
                    tbIngGasNoOpe,
                    new String[]{
                        "INGRESOS Y GASTOS NO OPERACIONALES", "MONTO C$"
                    }
            ));

        }

        ef.setText(Empresa);
        lblPeriodo.setText(Periodo);

        lblTotIng.setText(totingresos + "");
        lblCostos.setText(totcostos + "");
        lblUtilidadBruta.setText(utilidadB + "");
        lblUtilidadOpe.setText(utilidadOP + "");
        lblUtilidadAntImp.setText(utilidadantimp + "");
        lblImpuestos.setText(impuestos + "");
        lblUtilidadNeta.setText(utilidadneta + "");
        lblPagoDividendos.setText(dividendos + "");
        lblUtilidadRetenida.setText(utilidadretenida + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblIngresos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblDesDev = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        ef = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblGastos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblUtilidadRetenida = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblImpuestos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        lblUtilidadAntImp = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblUtilidadNeta = new javax.swing.JLabel();
        lblPagoDividendos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblUtilidadBruta = new javax.swing.JLabel();
        lblCostos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TblCostos = new javax.swing.JTable();
        lblTotIng = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TblIngGasNoOpe = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        lblUtilidadOpe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BALANCE GENERAL");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));

        TblIngresos.setBackground(new java.awt.Color(255, 255, 255));
        TblIngresos.setForeground(new java.awt.Color(0, 0, 0));
        TblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "INGRESOS", "MONTO"
            }
        ));
        TblIngresos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(TblIngresos);

        TblDesDev.setBackground(new java.awt.Color(255, 255, 255));
        TblDesDev.setForeground(new java.awt.Color(0, 0, 0));
        TblDesDev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "( - ) DESCUENTOS Y DEVOLUCIONES", "MONTO"
            }
        ));
        TblDesDev.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(TblDesDev);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("UTILIDAD BRUTA:");

        ef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ef.setForeground(new java.awt.Color(0, 0, 0));
        ef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ef.setText("ESTADO DE RESULTADO");

        lblEmpresa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("EMPRESA");

        lblPeriodo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        lblPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeriodo.setText("00/00/00");

        TblGastos.setBackground(new java.awt.Color(255, 255, 255));
        TblGastos.setForeground(new java.awt.Color(0, 0, 0));
        TblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "GASTOS", "MONTO"
            }
        ));
        TblGastos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setViewportView(TblGastos);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("UTILIDAD RETENIDA:");

        lblUtilidadRetenida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUtilidadRetenida.setForeground(new java.awt.Color(0, 0, 0));
        lblUtilidadRetenida.setText("00000");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("UTILIDAD ANTES DE IMPUESTOS:");

        lblImpuestos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImpuestos.setForeground(new java.awt.Color(0, 0, 0));
        lblImpuestos.setText("00000");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("IMPUESTOS:");

        lblUtilidadAntImp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUtilidadAntImp.setForeground(new java.awt.Color(0, 0, 0));
        lblUtilidadAntImp.setText("00000");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("UTILIDAD NETA:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("PAGO DE DIVIDENDOS:");

        lblUtilidadNeta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUtilidadNeta.setForeground(new java.awt.Color(0, 0, 0));
        lblUtilidadNeta.setText("00000");

        lblPagoDividendos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPagoDividendos.setForeground(new java.awt.Color(0, 0, 0));
        lblPagoDividendos.setText("00000");

        lblUtilidadBruta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUtilidadBruta.setForeground(new java.awt.Color(0, 0, 0));
        lblUtilidadBruta.setText("00000");

        lblCostos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCostos.setForeground(new java.awt.Color(0, 0, 0));
        lblCostos.setText("00000");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("COSTOS DE VENTA:");

        TblCostos.setBackground(new java.awt.Color(255, 255, 255));
        TblCostos.setForeground(new java.awt.Color(0, 0, 0));
        TblCostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "COSTOS", "MONTO"
            }
        ));
        TblCostos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setViewportView(TblCostos);

        lblTotIng.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotIng.setForeground(new java.awt.Color(0, 0, 0));
        lblTotIng.setText("00000");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("VENTAS NETAS:");

        TblIngGasNoOpe.setBackground(new java.awt.Color(255, 255, 255));
        TblIngGasNoOpe.setForeground(new java.awt.Color(0, 0, 0));
        TblIngGasNoOpe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "INGRESOS Y GASTOS NO OPERACIONALES", "MONTO"
            }
        ));
        TblIngGasNoOpe.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane7.setViewportView(TblIngGasNoOpe);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("UTILIDAD OPERATIVA:");

        lblUtilidadOpe.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUtilidadOpe.setForeground(new java.awt.Color(0, 0, 0));
        lblUtilidadOpe.setText("00000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(145, 145, 145)
                                .addComponent(lblCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(lblPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12))
                                    .addGap(123, 123, 123)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUtilidadNeta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPagoDividendos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane5)
                                .addComponent(jScrollPane3)
                                .addComponent(jSeparator1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(53, 53, 53))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(102, 102, 102)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUtilidadAntImp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(108, 108, 108))
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUtilidadRetenida, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(107, 107, 107))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUtilidadBruta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104))
                                .addComponent(jSeparator4)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(167, 167, 167)
                                .addComponent(lblTotIng, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(129, 129, 129)
                                .addComponent(lblUtilidadOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ef, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTotIng))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblCostos))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblUtilidadBruta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblUtilidadOpe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblUtilidadAntImp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblImpuestos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblUtilidadNeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagoDividendos)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblUtilidadRetenida))
                .addGap(16, 16, 16))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblCostos;
    private javax.swing.JTable TblDesDev;
    private javax.swing.JTable TblGastos;
    private javax.swing.JTable TblIngGasNoOpe;
    private javax.swing.JTable TblIngresos;
    private javax.swing.JLabel ef;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCostos;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblPagoDividendos;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblTotIng;
    private javax.swing.JLabel lblUtilidadAntImp;
    private javax.swing.JLabel lblUtilidadBruta;
    private javax.swing.JLabel lblUtilidadNeta;
    private javax.swing.JLabel lblUtilidadOpe;
    private javax.swing.JLabel lblUtilidadRetenida;
    // End of variables declaration//GEN-END:variables

    public void setData(ArrayList<accountsTableModel> ingresos, ArrayList<accountsTableModel> costos, ArrayList<accountsTableModel> gastos, String text, String text0, float totingresos, float totcostos, float totgastos, float utilidadB, float utilidadOP, float utilidadantimp, float impuestos, float utilidadneta, float utilidadretenida) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
